# Generated by Django 4.2.10 on 2024-02-23 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_profile_cat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="cat",
        ),
    ]
