# Generated by Django 4.2.10 on 2024-02-23 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meal", "0002_remove_meal_meal_meal_meal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meal",
            name="hungry_when_eating",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meal",
            name="stop_eating_not_hungry",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meal",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
