# Generated by Django 4.2.10 on 2024-03-20 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0004_nutrition_alter_meal_meal_type_fooditem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fooditem",
            name="meal",
        ),
    ]
